# This file is generated by Antidote from ~/.zsh_plugins.txt.
# It is kept in the repo as a placeholder. The actual bundle will be regenerated
# automatically by .zshrc if this file is missing, outdated, or contains invalid paths.
# 
# This stub ensures the file exists so the symlink works, but the real content
# will be generated by Antidote on first shell startup in each environment.


